import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "./globals.css"
import Header from '../components/header'
import ThemeContextProvider from "@/context/theme-context";
import ActiveSectionContextProvider from "@/context/active-section-context";
import ParallaxDivs from '@/components/parallax-divs';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth bg-zinc-100'>
      
      <body className={`${inter.className}   text-gray-950 relative`}>

     
     
        <ThemeContextProvider>
        <ParallaxDivs/>
        <ActiveSectionContextProvider>
            <Header />
            {children}
       

      
          </ActiveSectionContextProvider>
          </ThemeContextProvider>


      </body>
    
    </html>
  )
}
